package com.aymen.store.model.Enum

enum class Type {

    USER_SEND_CLIENT_COMPANY ,

    COMPANY_SEND_CLIENT_COMPANY ,

    COMPANY_SEND_PROVIDER_USER ,

    COMPANY_SEND_PROVIDER_COMPANY ,

    COMPANY_SEND_PARENT_COMPANY ,

    USER_SEND_WORKER_COMPANY ,

    COMPANY_SEND_WORKER_USER ,

    OTHER
}